easy peasy
VerinFast/verinfast pull request #387
Opened 2024-05-21 17:21 UTC by aylusltd

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-05-29 19:43 UTC, aylusltd commented on src/verinfast/agent.py
> +        merge = std_exec(["git", "show", hash, "|", "grep", "'^Merge: .* .*$'"])
rev-list doesn't take a hash as an argument

2024-07-01 13:53 UTC, SeanTConrad requested changes

2024-07-01 13:53 UTC, SeanTConrad commented on src/verinfast/agent.py
> +        merge = std_exec(["git", "show", hash, "|", "grep", "'^Merge: .* .*$'"])
I'm getting this error when testing:
```
Your branch is up to date with 'origin/main'.
2024-07-01 09:51:46 Gathering source code statistics for: atd.git
fatal: ambiguous argument '|': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

2024-07-01 18:11 UTC, SeanTConrad approved these changes

2024-07-01 18:11 UTC, merged