Add branch
VerinFast/verinfast pull request #391
Opened 2024-05-23 14:41 UTC by chrisperez626

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-05-23 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StartupOS/verinfast?pullRequest=391) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StartupOS/verinfast?pullRequest=391) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: chrisperez626<br/>:white_check_mark: SeanTConrad<br/>:white_check_mark: verinfast<br/>:white_check_mark: dependabot[bot]<br/>:white_check_mark: mnyon-grandkru<br/>:white_check_mark: aylusltd<br/>:x: olaoluwasalami<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StartupOS/verinfast?pullRequest=391) it.</sub>

2024-06-28 13:17 UTC, SeanTConrad commented on src/verinfast/agent.py
> +            template_definition["dependencies"] = json.load(dependencies_output_file)
@chrisperez626 Are both assignments to` template_definition["dependencies"] `necessary?

2024-06-28 13:18 UTC, SeanTConrad requested changes
One question on `template_definition["dependencies"]`

2024-07-01 13:47 UTC, chrisperez626 commented on src/verinfast/agent.py
> +            template_definition["dependencies"] = json.load(dependencies_output_file)
You're right I think I just forgot to remove one.

2024-07-01 15:54 UTC, SeanTConrad approved these changes

2024-07-01 15:54 UTC, merged